# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myQuote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quote',
            managers=[
                ('wishlistManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
